security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt
  providers:
    users_in_memory:
      memory: null
    in_database:
      entity:
        class: App\Entity\User
        property: login
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      stateless: true
      anonymous: true
      user_checker: App\Security\UserChecker
      pattern: ^/api/login_check
      provider: in_database
      json_login:
        check_path: /api/login_check
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
    default:
      anonymous: lazy
      pattern: ^/
      user_checker: App\Security\UserChecker
      provider: in_database
      form_login:
        login_path: login_user
        check_path: login_user
      logout:
        path: logout_user
        target: login_user

  access_control: