vich_uploader:
    db_driver: orm

    mappings:
            guide_image:
                uri_prefix: /images/guides
                upload_destination: '%kernel.project_dir%/public/images/guides'

            utilisateur_image:
                            uri_prefix: /images/guides
                            upload_destination: '%kernel.project_dir%/public/images/guides'

            photo_medias:
                  uri_prefix: /images/medias
                  upload_destination: '%kernel.project_dir%/public/images/medias'

            experience_medias:
                  uri_prefix: /images/experiences
                  upload_destination: '%kernel.project_dir%/public/images/experiences'

