<?php

    namespace App\Controller\Account;

    use App\Entity\Guide;
    use App\Entity\Media;
    use App\Entity\ValeurReferentiel;
    use App\Form\ActivitesType;
    use App\Form\MediaType;
    use App\Form\SocialMediaType;
    use App\Repository\GuideRepository;
    use App\Repository\ValeurReferentielRepository;
    use Doctrine\ORM\Mapping\Builder\FieldBuilder;
    use EasyCorp\Bundle\EasyAdminBundle\Collection\FieldCollection;
    use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
    use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
    use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
    use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
    use EasyCorp\Bundle\EasyAdminBundle\Config\KeyValueStore;
    use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
    use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
    use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
    use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
    use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
    use EasyCorp\Bundle\EasyAdminBundle\Field\Field;
    use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
    use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
    use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
    use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
    use EasyCorp\Bundle\EasyAdminBundle\Provider\FieldProvider;
    use Symfony\Bridge\Doctrine\Form\Type\EntityType;
    use Symfony\Component\DomCrawler\Field\FileFormField;
    use Symfony\Component\Form\Extension\Core\Type\CollectionType;
    use Vich\UploaderBundle\Form\Type\VichImageType;

    class GuideCrudController extends AbstractCrudController
    {

        public static function getEntityFqcn(): string
        {
            return Guide::class;
        }

        public function configureActions(Actions $actions): Actions
        {
            return $actions
                ->add(Crud::PAGE_INDEX, Action::DETAIL)
                ->remove(Crud::PAGE_DETAIL, Action::INDEX)
                ->remove(Crud::PAGE_DETAIL, Action::DELETE);
        }


        public function configureResponseParameters(KeyValueStore $responseParameters): KeyValueStore
        {
            return parent::configureResponseParameters($responseParameters); // TODO: Change the autogenerated stub
        }

        public function configureFields(string $pageName): iterable
        {
            $repo = $this->getDoctrine()->getRepository(ValeurReferentiel::class);
            $vrs = $repo->findBy(["id_ref" => 1]);
            $builder = [
                TextField::new('nom'),
                TextField::new('prenom'),
                TextField::new('phone'),
                TextEditorField::new('description'),
                TextField::new('location'),
                ImageField::new('imageName')->onlyOnDetail()
                    ->setBasePath("images/guides")
                    ->setUploadDir("images/guides")
                    ->addCssClass("ea-vich-image"),
                TextEditorField::new('imageFile')->onlyOnForms()
                    ->setFormType(VichImageType::class),
                ArrayField::new('links')->onlyOnDetail(),
                TextEditorField::new('links')->onlyOnForms()->
                setFormType(SocialMediaType::class),
                AssociationField::new('activites')->onlyOnForms(),
                AssociationField::new('activites')->onlyOnDetail(),
//                CollectionField::new('medias')
//                    ->setEntryType(MediaType::class)
//                    ->onlyOnForms(),
//                CollectionField::new('medias')
//                    ->setEntryType(MediaType::class)
//                    ->onlyOnDetail(),

            ];


            return $builder;

        }

        public function configureAssets(Assets $assets): Assets
        {
            return $assets
                ->addCssFile('https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.css')
                ->addJsFile("https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js")
                ->addJsFile("https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.proto.js")
                ->addHtmlContentToBody('<script>
                $(document).ready(function () {$(".chosen-select").chosen(); }
                </script>');
        }


    }
